e-Infrastructure for Virtual Research Environments -*- mode: org; -*-

#+FILETAGS: :Sage:Financement:

* TODO Consortium
** Get in touch with GAP, Singular, Pari, ...
* Call 3 Topic 9-2015 EINFRA-9: e-Infrastructure for Virtual Research Environment
** Suggested EU contribution per proposal: 2 to 8 M€ ; Total budget: 42 M€
** Dates: 14/01/2015
- H2020-EINFRA-2014-1 15/04/2014
- H2020-EINFRA-2014-2 02/09/2014
- H2020-EINFRA-2015-1 14/01/2015(tbc)
** European contacts: Antonios Barbas
   See file:Documentation/Contacts.docx
** Definition:
- Groups of researchers, typically widely dispersed, who are working
  together
- through ubiquitous, trusted and easy access to services for
  scientific data, computing and networking
- in a collaborative, virtual environment:
  > the e-Infrastructures
** Characteristics:
- Address the needs of specific scientific communities – in support of
  e-Science;
- Have users from both academia and industry;
- Involve bottom-up research and develop user-oriented services;
- Are based on e-infrastructures

** Specific challenge:
- Capacity building in interdisciplinary research
- through community-led development and deployment of service-driven
  digital environments
- for large-scale cross-disciplinary research collaboration and data
  interoperability
** Expected impact:
- More effective collaboration between researchers and increased
  take-up of collaborative research by new disciplines;
- Easier discovery, access and re-use of data, resulting in higher
  productivity of researchers;
- Accelerate innovation via access to integrated digital research
  resources across disciplines;
** Scope: Proposals are expected to
Notations: [X]: easy to argue; [?]: we have some lead, but that will take some arguing
- [?] Integrate resources across all layers of the e-infrastructure
  (networking, computing, data, software, user interfaces) to foster
  cross-disciplinary data interoperability
- [?] Build on requirements from real use cases, i.e. integrate
  heterogeneous data from multiple sources and re-use tools and
  services from existing infrastructures
- [X] Target any area of Science and Technology, especially
  interdisciplinary ones, including ICT, mathematics, web science and
  social sciences and humanities
- [X] Use standardised building blocks and workflows, well-documented
  interfaces and interoperable components;
- Define semantics, ontologies and metadata to enable data citation
  and promote data sharing, as to ensure interoperability;
- [X] Target easy-to-use functionalities; and indicate the number of
  researchers they target as potential users;
** Specific conditions for the Call on e-Infrastructures:
- [X?] Proposals should be structured around Networking, Service
  and Joint Research Activities
- [X] The Software to be developed needs to be open source
- [ ] A Data Management Plan to be developed enabling data preservation,
  on-line discoverability, authorisation and re-use of data
- [X] Clear Metrics (KPIs) to be proposed and used;
- [?] Open Access to Publications resulting from the project;
- [X] Usefulness of services to the end user community and
      financial sustainability to be ensured;
** Where should the emphasis be?
- [?] Services
- [X] Thinking innovation
      With both suppliers or users
- [X] Mainstreaming skills development
- [ ] Integration between data and computing
- [X] Business plans for financial sustainability
  ...and partnerships with the private sector
- [ ] Supporting policies
- [X] open data and software
- [X] Sharing basic operations services and building blocks
- [X] Monitoring performance (KPIs)
** Simplified funding model
   - Up to 100% for Research and Innovation
   - Flat 25% rate for indirect costs (overhead?)
* Sensitive points
** Articulation w.r.t. sagemath-cloud and the IPython notebook
    Both projects fit very well within the theme of the call. So we
    need to specifically mention them as sister projects that will
    contribute essential building blocs, possibly include some work on
    those projects, and explain what the core of our contribution will
    be.
** Big Data
    This is a central keyword in the call; what do we have to offer in
    this direction, beside mentioning [[http://lmfdb.org][LMFDB]] as sister project?
** Industrial collaborations
   Eugénia Shadlova: those are very welcome, but not necessary.
   Directions to explore:
   - [[http://logilab.fr][Logilab]]?
   - Label by the [[http://www.gt-logiciel-libre.org/][open source software work group]] of the [[http://systematic-paris-region.org/][Systematic Paris Region Systems & ICT Cluster]]?
* Références
  - http://ec.europa.eu/research/participants/portal/
  - http://ec.europa.eu/research/participants/portal/desktop/en/opportunities/h2020/topics/2144-einfra-9-2015.html
  - http://ec.europa.eu/digital-agenda/en/news/information-days-horizon-2020-research-infrastructures-work-programme-2014-2015-focus-e
  - file:Documentation/SubmissionAndEvaluation.ppt
* TODO Choose an acronym
* WAIT Support from CNRS's INS2I for preparing an application
  http://www.cnrs.fr/ins2i/spip.php?article669
  The CNRS INS2I institute is offering support (up to 5000 euros) for
  preparing such proposals. This money could be used e.g. to organize
  a Sage Days this year geared toward this grant (and real work
  too!). To apply for such support we need to file a 3-5 page draft
  with a tentative list of partner institutions and number of
  participant in each of them.
** Submission
   DEADLINE: <2014-03-21 ven.>
  Les propositions doivent être soumises par email à Michel Renovell,
  délégué scientifique, avec copie à Corinne Poulain.
  Michel.Renovell(at)cnrs-dir.fr
  corinne.poulain(at)cnrs-dir.fr

  Conversion to docx:

  \sage -> \sage{}
  \TODO -> {}
  pandoc -t docx project-description.tex -o project-description.docx
  justification gauche et droite
  marges: 2cm
  fontes 11pt
  Check that the first section fits on the first page
  Check that the document fits in five pages
** Results
   SCHEDULED: <2014-04-15 mar.>
** Application file
  - La description thématique et scientifique du projet (Document Word)
    3-5 pages

    1. le contexte et le thème scientifique
    2. Les challenges et l'originalité de la solution
    3. Les retombées scientifiques et sociétales

    file:Documentation/SupportFromINS2I/Thiery-Sage-H2020-2014.docx

  - Les données relatives aux participants du projet (Feuille Excel).
    file:SupportFromINS2I/Thiery-Sage-h2020-2014.xls
* Suggestions from Eugénia Shadlova (european projects service at Université Paris Sud)
0. La préexistence d'une communauté est un bon point

1. Il faudra justifier l'apport d'un projet Européen:
    - Plus grande ouverture vers d'autres pays Européens
    - Ouverture vers d'autres disciplines

2. Assurez-vous que ce que vous souhaitez mettre en place correspond
   bien à la définition du Virtual research environment - une étape
   au-dessus du logiciel, une "boite à outils"qui aide les chercheurs
   des disciplines différentes à gérer des séries de tâches de plus en
   plus complexes impliquées dans leurs recherches.

3. Attention, l'appel met beaucoup l'accent sur "data exploitation",
   ce qui n'est pas forcément présent dans votre projet, il y a
   peut-être moyen d'y intégrer cet aspect ?

4. "they should re-use tools and services from existing
   infrastructures"(v.le texte de l'appel) - c'est très positif pour
   nous vue que votre projet se base sur des outils existants

5. "they may also support proof of concept, prototyping and deployment
   of advanced data services and environments, and access to
   top-of-the range connectivity and computing" - ça c'est un aspect
   très important qui doit absolument être pris en compte

6. Enfin, il y aura une grande communauté scientifique derrière cet
   appel (projets ESFRI), mais la carte que vous aurez à jouer par
   rapport à eux, c'est que votre projet porte sur les maths, et il y
   aura très peu de matheux parmi les autres candidats. Il sera donc
   très important d'inclure dans votre projet des chercheurs en
   combinatoire, qui seront des end-users de votre logiciel, et de
   préférence quelques grands noms.

* Meeting with the infrastructure PCN of the french ministry of research
  <2014-02-10 lun. 16:00-17:00>
  JEAN-PIERRE CAMINADE <jean-pierre.caminade at recherche.gouv.fr>
  PCRI, accueil du bâtiment
